### PR TITLE
Header and page navigation

### PR DESCRIPTION
**Pull request by migueldlr**
Fixed most (if not all) page links on each page
Header is sticky but with modifications to save screen space

### CODE REVIEW

**Comment by 97chaebin** [comment]
is the navbar supposed to disappear when you scroll down the page?

**Review by 97chaebin — APPROVED** [review]

**Review by 97chaebin — CHANGES_REQUESTED** [review]
"Attend a Class/Event" should link the classes and events page and "Nutritional Resources" should link to the Resources page

**Review by Arthelon — APPROVED** [review]
lgtm

**Comment by migueldlr** [comment]
Nav changes are on Contentful, so I'm force-pushing this one hehe

**Pull request merged**
