### PR TITLE
added footer

### LINKED ISSUE #35: Footer
https://www.figma.com/file/6SnGmwXgJwpRojgPWXKkYn/Health-Families-Healthy-Futures-(HF)-%2F-Spr21?node-id=747%3A4552

### PR DESCRIPTION
**Pull request by vpatakottu**

### CODE REVIEW

**Review by 97chaebin — CHANGES_REQUESTED** [review]
"About Us", "Get Involved", "resources and Blog" spacing isn't even, too much space between the logo and next block of text

**Review by 97chaebin — APPROVED** [review]

**Comment by 97chaebin** [comment]
looks good!!

**Review by migueldlr — APPROVED** [review]
Great work! So many lines of code!

**Comment by migueldlr** [comment]
Closes #35

**Pull request merged**
